name: SSH server
on:
  watch:
    types: started
  repository_dispatch:
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
